select * from Category
select * from Recipe
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Falafel', 'Blötlägg kikärtorna i ca 1 liter vatten minst 12 timmar. Häll av kikärtorna och skölj. Låt rinna av i ett durkslag.  Skala och hacka lök och vitlök. Dela och kärna ur chilin och skär i bitar. Mixa lök, vitlök, chili, persilja och hackad koriander slätt i en matberedare. Lägg i en bunke. Mixa kikärterna till en grynig massa, tillsätt ev lite vatten. Mixa inte helt slätt. Lägg i bunken med mixade örter och tillsätt spiskummin, koriander, salt och bikarbonat. Tillsätt ev lite vatten, smeten ska vara lite smulig och klibbig. Hetta upp oljan till ca 180°C i en kastrull. Tryck och forma till ca 16 bollar för hand (för 4 port), alternativt med hjälp av en liten glasskopa eller två skedar. Lägg försiktigt ner i oljan. Fritera i omgångar tills de är gyllene ca 5 minuter. Lyft upp med en hålslev. Låt rinna av på lite hushållspapper och servera direkt.','2020-01-23',4)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Köttbullar i tomatsås', 'Koka pastan enligt anvisningen på förpackningen.Häll av oliver och kapris i en sil. Mortla fänkålsfröna.Stek köttbullarna i oljan i en stekpanna, krydda med fänkålsfrön.Sänk värmen och rör i pastasås, oliver och kapris i pannan. Låt sjuda 2 minuter.','2020-01-11',5)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Pasta polpette', 'Skala lök och vitlök. Hacka löken och riv vitlöken.Ansa och skiva fänkålen tunt.Fräs löken, vitlöken och fänkålen i olivoljan i en gryta, tills de börjar bli lite mjuka.Häll på tomatsåsen, koka sakta ca 10 minuter.Stek köttbullarna i smöret enligt anvisningen på förpackningen.Koka pastan i saltat vatten enligt anvisningen på förpackningen. Häll av pastan i ett durkslag men spara 1 dl av kokvattnet (för 4 port).Blanda pastan med tomatsås, kokvatten och spenat. Smaka av med salt och peppar.','2020-01-23',5)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Pasta med jordärtskockssås och portabello', 'Tina sojabönorna.Sätt på en kastrull med vatten till pastan och som också rymmer sojabönorna.Skala och skiva lök och jordärtskocka. Fräs dem i smöret i en kastrull.Pressa i vitlöken och tillsätt grädden och buljongen. Låt sjuda ca 10 minuter. Mixa till en slät sås med en stavmixer och smaka av med salt, peppar och några droppar citronsaft.Koka pastan enligt anvisningen på förpackningen. Koka sojabönorna tillsammans med pastan de 2 sista minuterna på pastans koktid.Ansa och skär portabellon i skivor. Stek svampen i olivoljan i en stekpanna och krydda med salt och chiliflakes. Blanda såsen med pastan och spenaten, toppa med svamp.','2019-02-18',5)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Vegolasagne med zucchini och spenat', 'Sätt ugnen på 180°C.Hacka schalottenlöken, purjolöken och vitlöken fint. Skär zucchinin i tunna skivor på längden.Fräs löken tills den är mjuk och genomskinlig (den ska inte få färg). Blanda ner spenaten och vänta till den krymper ihop. Tillsätt sojagrädde och sojadryck. Blanda ner limejuice, dragon, muskot. Smaka av med salt och peppar.Varva sås och lasagneplattor, zucchiniskivor och hälften av osten i en ugnssäker form. Avsluta med sås och toppa med resten av osten.Grädda i mitten av ugnen i ca 30 minuter till det bubblar på ytan och osten är gyllenbrun.','2019-06-08',4)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Kryddig kebab med renskav', 'Skala och riv vitlöken. Blanda den med gräddfil. Smaksätt med salt och peppar.Dela och ta bort kärnorna på tomaterna. Skär tomaterna i små tärningar. Skala och hacka löken fint. Hacka persiljan. Blanda tomat, lök och persilja med harissa.Ansa, skölj och strimla salladen fint.Stek renskaven i omgångar i oljan i en stekpanna, krydda med salt, peppar och ras el hanout.Värm pitabröden enligt anvisningen på förpackningen.Fyll pitabröden med renskav, sallad och tomat- och löksalsa. Ringla över vitlökssås och toppa gärna med feferoni.','2019-11-19',1)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Korean fried chicken', 'Skär varje kycklinglårfilé i 3 bitar. Vänd först kycklingen i majsstärkelsen och sedan i frityrsmeten så de täcks runtom. Vänd sedan en gång till i majsstärkelsen. Värm oljan till 180°C i en stor kastrull.Fritera kycklingen i omgångar ca 10 minuter eller tills kycklingen är genomstekt och krispig. Lägg på galler eller hushållspapper och låt rinna av. Om du vill ha kycklingen extra krispig friterar du den en gång till.','2019-04-13',2)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Sötstark kyckling med krispig blomkål', 'Tina blomkålen (om fryst används).Sätt ugnen på 250°C och sätt in en plåt.Kryddig kyckling: Skär varje kyckling i 3 bitar. Blanda salt och oregano och vänd runt kycklingen i blandningen.Krispig blomkål: Tillaga blomkålen i ugnen enligt anvisningen på förpackningen. Koka bulgurn enligt anvisningen på förpackningen.Kryddig kyckling: Stek kycklingen i oljan i en stekpanna i 3 minuter. Sänk värmen och rör i sweet chilisås, vatten och soja. Sjud i 3 minuter till en såsig konsistens (kontrollera att kycklingen är klar, innertemperaturen ska vara 72°C).','2020-01-03',2)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Ugnsbakad fisk med saffranssmetana', 'Tina fisken och bönorna.Sätt ugnen på 200°C.Mos: Koka upp vatten i en kastrull. Skala och skär potatisen i mindre bitar. Lägg i potatisen och låt småkoka under lock tills den är mjuk. Lägg bönorna i en ugnsform och lägg på fisken. Krydda med salt och peppar och ställ in mitt i ugnen ca 15 minuter eller tills innertemperaturen på fisken är 56°C.','2019-08-27',3)
insert into Recipe (Title, Post, CreateDate, CategoryID) values('Fiskgryta med saffransaioli och baguette', 'Fiskgryta: Tina musslorna och torsken om fryst används.Bröd: Sätt ugnen på 225°C.Fiskgryta: Skala lök, morötter och potatis och skär dem i små tärningar. Fräs lök, morötter och potatis i oljan i en gryta några minuter och pressa i vitlöken. Rör ner passerade tomater, vatten och smulad buljongtärning. Låt koka upp. Sänk värmen och låt grytan sjuda tills grönsakerna är nästan mjuka, ca 10 minuter.Bröd: Grädda bröden enligt anvisningen på förpackningen. Aioli: Blanda majonnäsen med saffranet och smaka av med salt och peppar.Fiskgryta: Skär fisken i bitar och lägg ner i grytan. Låt sjuda ca 5 minuter.','2020-01-09',3)




select* from Recipe
insert into Recipe (Title, Post, CreateDate, Category) values('Falafel', 'Blötlägg kikärtorna i ca 1 liter vatten minst 12 timmar. Häll av kikärtorna och skölj. Låt rinna av i ett durkslag.  Skala och hacka lök och vitlök. Dela och kärna ur chilin och skär i bitar. Mixa lök, vitlök, chili, persilja och hackad koriander slätt i en matberedare. Lägg i en bunke. Mixa kikärterna till en grynig massa, tillsätt ev lite vatten. Mixa inte helt slätt. Lägg i bunken med mixade örter och tillsätt spiskummin, koriander, salt och bikarbonat. Tillsätt ev lite vatten, smeten ska vara lite smulig och klibbig. Hetta upp oljan till ca 180°C i en kastrull. Tryck och forma till ca 16 bollar för hand (för 4 port), alternativt med hjälp av en liten glasskopa eller två skedar. Lägg försiktigt ner i oljan. Fritera i omgångar tills de är gyllene ca 5 minuter. Lyft upp med en hålslev. Låt rinna av på lite hushållspapper och servera direkt.','2020-01-23','Vegan')
insert into Recipe (Title, Post, CreateDate, Category) values('Köttbullar i tomatsås', 'Koka pastan enligt anvisningen på förpackningen.Häll av oliver och kapris i en sil. Mortla fänkålsfröna.Stek köttbullarna i oljan i en stekpanna, krydda med fänkålsfrön.Sänk värmen och rör i pastasås, oliver och kapris i pannan. Låt sjuda 2 minuter.','2020-01-11','Pasta')
insert into Recipe (Title, Post, CreateDate, Category) values('Pasta polpette', 'Skala lök och vitlök. Hacka löken och riv vitlöken.Ansa och skiva fänkålen tunt.Fräs löken, vitlöken och fänkålen i olivoljan i en gryta, tills de börjar bli lite mjuka.Häll på tomatsåsen, koka sakta ca 10 minuter.Stek köttbullarna i smöret enligt anvisningen på förpackningen.Koka pastan i saltat vatten enligt anvisningen på förpackningen. Häll av pastan i ett durkslag men spara 1 dl av kokvattnet (för 4 port).Blanda pastan med tomatsås, kokvatten och spenat. Smaka av med salt och peppar.','2020-01-23','Pasta')
insert into Recipe (Title, Post, CreateDate, Category) values('Pasta med jordärtskockssås och portabello', 'Tina sojabönorna.Sätt på en kastrull med vatten till pastan och som också rymmer sojabönorna.Skala och skiva lök och jordärtskocka. Fräs dem i smöret i en kastrull.Pressa i vitlöken och tillsätt grädden och buljongen. Låt sjuda ca 10 minuter. Mixa till en slät sås med en stavmixer och smaka av med salt, peppar och några droppar citronsaft.Koka pastan enligt anvisningen på förpackningen. Koka sojabönorna tillsammans med pastan de 2 sista minuterna på pastans koktid.Ansa och skär portabellon i skivor. Stek svampen i olivoljan i en stekpanna och krydda med salt och chiliflakes. Blanda såsen med pastan och spenaten, toppa med svamp.','2019-02-18','Pasta')
insert into Recipe (Title, Post, CreateDate, Category) values('Vegolasagne med zucchini och spenat', 'Sätt ugnen på 180°C.Hacka schalottenlöken, purjolöken och vitlöken fint. Skär zucchinin i tunna skivor på längden.Fräs löken tills den är mjuk och genomskinlig (den ska inte få färg). Blanda ner spenaten och vänta till den krymper ihop. Tillsätt sojagrädde och sojadryck. Blanda ner limejuice, dragon, muskot. Smaka av med salt och peppar.Varva sås och lasagneplattor, zucchiniskivor och hälften av osten i en ugnssäker form. Avsluta med sås och toppa med resten av osten.Grädda i mitten av ugnen i ca 30 minuter till det bubblar på ytan och osten är gyllenbrun.','2019-06-08','Vegan')
insert into Recipe (Title, Post, CreateDate, Category) values('Kryddig kebab med renskav', 'Skala och riv vitlöken. Blanda den med gräddfil. Smaksätt med salt och peppar.Dela och ta bort kärnorna på tomaterna. Skär tomaterna i små tärningar. Skala och hacka löken fint. Hacka persiljan. Blanda tomat, lök och persilja med harissa.Ansa, skölj och strimla salladen fint.Stek renskaven i omgångar i oljan i en stekpanna, krydda med salt, peppar och ras el hanout.Värm pitabröden enligt anvisningen på förpackningen.Fyll pitabröden med renskav, sallad och tomat- och löksalsa. Ringla över vitlökssås och toppa gärna med feferoni.','2019-11-19','Kött')
insert into Recipe (Title, Post, CreateDate, Category) values('Korean fried chicken', 'Skär varje kycklinglårfilé i 3 bitar. Vänd först kycklingen i majsstärkelsen och sedan i frityrsmeten så de täcks runtom. Vänd sedan en gång till i majsstärkelsen. Värm oljan till 180°C i en stor kastrull.Fritera kycklingen i omgångar ca 10 minuter eller tills kycklingen är genomstekt och krispig. Lägg på galler eller hushållspapper och låt rinna av. Om du vill ha kycklingen extra krispig friterar du den en gång till.','2019-04-13','Kickling')
insert into Recipe (Title, Post, CreateDate, Category) values('Sötstark kyckling med krispig blomkål', 'Tina blomkålen (om fryst används).Sätt ugnen på 250°C och sätt in en plåt.Kryddig kyckling: Skär varje kyckling i 3 bitar. Blanda salt och oregano och vänd runt kycklingen i blandningen.Krispig blomkål: Tillaga blomkålen i ugnen enligt anvisningen på förpackningen. Koka bulgurn enligt anvisningen på förpackningen.Kryddig kyckling: Stek kycklingen i oljan i en stekpanna i 3 minuter. Sänk värmen och rör i sweet chilisås, vatten och soja. Sjud i 3 minuter till en såsig konsistens (kontrollera att kycklingen är klar, innertemperaturen ska vara 72°C).','2020-01-03','Kyckling')
insert into Recipe (Title, Post, CreateDate, Category) values('Ugnsbakad fisk med saffranssmetana', 'Tina fisken och bönorna.Sätt ugnen på 200°C.Mos: Koka upp vatten i en kastrull. Skala och skär potatisen i mindre bitar. Lägg i potatisen och låt småkoka under lock tills den är mjuk. Lägg bönorna i en ugnsform och lägg på fisken. Krydda med salt och peppar och ställ in mitt i ugnen ca 15 minuter eller tills innertemperaturen på fisken är 56°C.','2019-08-27','Fisk')
insert into Recipe (Title, Post, CreateDate, Category) values('Fiskgryta med saffransaioli och baguette', 'Fiskgryta: Tina musslorna och torsken om fryst används.Bröd: Sätt ugnen på 225°C.Fiskgryta: Skala lök, morötter och potatis och skär dem i små tärningar. Fräs lök, morötter och potatis i oljan i en gryta några minuter och pressa i vitlöken. Rör ner passerade tomater, vatten och smulad buljongtärning. Låt koka upp. Sänk värmen och låt grytan sjuda tills grönsakerna är nästan mjuka, ca 10 minuter.Bröd: Grädda bröden enligt anvisningen på förpackningen. Aioli: Blanda majonnäsen med saffranet och smaka av med salt och peppar.Fiskgryta: Skär fisken i bitar och lägg ner i grytan. Låt sjuda ca 5 minuter.','2020-01-09','Fisk')
